from pymycobot.mycobot280 import MyCobot280
import time

mc = MyCobot280("COM5", 115200)
time.sleep(2)

print("SphinSaure 1s22s22p63s23p63d104s24p64d104f145s25p65d105f106s26p67s2")
print("Test start...")
# ==================================================Test 1: System status====================================================
print("Test 1: System status")
print("固件版本号: ", mc.get_system_version())
print("float固件版本：", mc.get_basic_version())
print("错误信息: ", mc.get_error_information())
print("0：无错误信息。1～6：对应关节超出极限位置。16～19：碰撞保护。32：运动学逆解无解。33～34：直线运动无相邻解。")
print("Test 1 finish")
# ==================================================Test 2: Robot status====================================================
print("Test 2: Robot status")
print("打开通信: ", mc.power_on())
print("1 means success")
print("上电状态: ", mc.is_power_on())
print("1: 上电 0: 掉电 -1: 错误")
print("Test 2 finish")
# ==================================================Test 3: Control the angles====================================================
print("Test 3: Control the angles")
print("single angle: ")
print("set angle, fast:")
mc.send_angle(1, 30, 80)
time.sleep(5)
print("set angle, slow:")
mc.send_angle(1, 60, 20)
time.sleep(5)
print("get angles:", mc.get_angles())
print("set angles, fast:")
mc.send_angles([20, -20, 20, -20, 20, -20], 50)
time.sleep(5)
print("set angles, slow:")
mc.send_angles([-20, 20, -20, 20, -20, 20], 10)
time.sleep(5)
mc.send_angles([0, 0, 0, 0, 0, 0], 50)
time.sleep(5)
print("Test 3 finish")
# ==================================================Test 4: Control the coordinates====================================================
print("Test 4: Control the coordinates")
print("single coordinate: ")
print("set coordinate, fast:")
mc.send_coord(1, 100, 80)
time.sleep(5)
print("set coordinate, slow:")
mc.send_coord(2, -60, 20)
time.sleep(5)
print("get coordinates:", mc.get_coords())
print("set coordinates, fast, linear:")
mc.send_coords([57.0, -107.4, 316.3, -93.81, -12.71, -163.49], 80, 1)
time.sleep(5)
print("set coordinates, slow, linear:")
mc.send_coords([-57.0, 107.4, -10.0, 93.81, 12.71, 163.49], 20, 1)
time.sleep(5)
print("set coordinates, normal, unlinear:")
mc.send_coords([57.0, -107.4, 316.3, -93.81, -12.71, -163.49], 20, 0)
time.sleep(5)
print("Test 4 finish")
# ==================================================Test 5: Control the input/output====================================================
print("Test 5: Control the input/output")
mc.set_color(255, 135, 153)
time.sleep(2)
mc.set_color(198, 113, 255)
time.sleep(2)
mc.set_color(255, 211, 0)
time.sleep(2)
print("Test 5 finish")
# ======================================================================================================================================
print("... all test finish.")